language: go
go:
  - 1.8
env:
  - GOARCH=amd64
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - xvfb
    - gtk+3.0
    - libgtk-3-dev
    - libcairo2-dev
    - libglib2.0-dev
notifications:
  email: false
before_install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/0.12.3 && go install && cd -
  - glide install
  - ls -la
  - ln -sr vendor/github.com src/github.com
  - export DISPLAY=:99.0
  - sudo /usr/bin/Xvfb $DISPLAY 2>1 > /dev/null &
  - export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _| cut -d '_' -f 1-2)
  - export Glib_VERSION=$(pkg-config --modversion glib-2.0)
  - export Cairo_VERSION=$(pkg-config --modversion cairo)
  - export Pango_VERSION=$(pkg-config --modversion pango)
install:
  - go install -v -tags "gtk_${GTK_VERSION}"
script:
  - go test -v -tags "gtk_${GTK_VERSION}"