language: go

sudo: false

go:
  - master

os:
  - linux

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get -q update
  - sudo apt-get install -y glide libgtk-3-dev libcairo2-dev libglib2.0-dev
  - glide install
  - ln -sr vendor/github.com src/github.com

script: go test -v -tags gtk_3_18

notifications:
  email: false